<?php
# This file was automatically generated by the MediaWiki 1.29.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if (!defined('MEDIAWIKI')) {
	exit;
}

## Uncomment this to disable output compression
$wgDisableOutputCompression = true;

$wgSitename      = "name of wiki";
$wgMetaNamespace = "项目";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";
$wgStylePath  = "$wgScriptPath/skins";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://127.0.0.1";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgScriptPath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail     = false;
$wgEnableUserEmail = false; # UPO

$wgEmergencyContact = "apache@" . \JENV\BASE_DOMAIN;
$wgPasswordSender   = "apache@" . \JENV\BASE_DOMAIN;

$wgEnotifUserTalk      = false; # UPO
$wgEnotifWatchlist     = false; # UPO
$wgEmailAuthentication = false;

## Database settings
$wgDBtype     = "mysql";
$wgDBserver   = \JENV\CONIG_DB_SERVER . ':' . \JENV\CONIG_DB_PORT;
$wgDBname     = "mediawiki";
$wgDBuser     = "root";
$wgDBpassword = \JENV\CONIG_DB_SUPER_PASSWORD;

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=utf8";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads             = true;
$wgUseImageMagick            = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "zh-cn";

$wgSecretKey = "762de88a5e7c9d241e3c5e94257a4eb426cd3c01edebe5257a50168bbb62d3bc";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "8d723bfd26cb3bc0";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText = "知识共享署名-相同方式共享";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin('CologneBlue');
wfLoadSkin('Modern');
wfLoadSkin('MonoBook');
wfLoadSkin('Vector');

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension('Cite');
wfLoadExtension('Gadgets');
wfLoadExtension('InputBox');
wfLoadExtension('Interwiki');
wfLoadExtension('LocalisationUpdate');
wfLoadExtension('ParserFunctions');
wfLoadExtension('PdfHandler');
wfLoadExtension('Renameuser');
wfLoadExtension('SpamBlacklist');
wfLoadExtension('SyntaxHighlight_GeSHi');
wfLoadExtension('TitleBlacklist');
wfLoadExtension('WikiEditor');
wfLoadExtension('ConfirmEdit');
wfLoadExtension('Nuke');
# wfLoadExtension('SimpleAntiSpam');
# wfLoadExtension('RecentChangesCleanup');

# End of automatically generated settings.
# Add more configuration options below.

$wgGroupPermissions['sysop']['recentchangescleanup']                = true;
$wgGroupPermissions['recentchangescleanup']['recentchangescleanup'] = true;
# End of automatically generated settings.
# Add more configuration options below.

# Enables use of WikiEditor by default but still allow users to disable it in preferences
$wgDefaultUserOptions['usebetatoolbar']     = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;

# Displays the Preview and Changes tabs
$wgDefaultUserOptions['wikieditor-preview'] = 1;

# Displays the Publish and Cancel buttons on the top right side
$wgDefaultUserOptions['wikieditor-publish'] = 1;

$wgGroupPermissions['sysop']['tboverride'] = false;

$wgTitleBlacklistSources = [
		[
				'type' => TBLSRC_LOCALPAGE,
				'src'  => 'MediaWiki:Titleblacklist',
		],
		[
				'type' => TBLSRC_URL,
				'src'  => 'http://meta.wikimedia.org/wiki/MediaWiki:Titleblacklist',
		],
		[
				'type' => TBLSRC_URL,
				'src'  => 'http://en.wikipedia.org/wiki/MediaWiki:Titleblacklist',
		],
];

#Prevent new user registrations
$wgGroupPermissions['*']['createaccount'] = false;
#$wgWhitelistAccount = array ( "user" => 0, "sysop" => 1, "developer" => 1 );
$wgAutoConfirmAge = 86400 * 30;

$wgFileExtensions = ['png', 'gif', 'jpg', 'jpeg', 'doc', 'zip', 'rar', 'pdf'];
//Because we use email addresses as our wiki's username, we have to add this line
$wgUserrightsInterwikiDelimiter = ' ';

$_debug                 = false;
$wgShowExceptionDetails = $_debug;
$wgDebugToolbar         = $_debug;
$wgShowDebug            = $_debug;
$wgDevelopmentWarnings  = $_debug;
